program: tests/main.py
method: random
metric: 
  goal: minimize
  name: validation_loss
parameters:
  num_encoder_layers:
    value: 3
  num_decoder_layers:
    value: 3
  batch_size:
    value: 32
  epochs:
    value: 10
  lr:
    value: 0.001
  T_max:
    value: 10