program: tests/main.py
method: random
metric: 
  goal: minimize
  name: validation_loss
parameters:
  num_encoder_layers:
    value: 3
  num_decoder_layers:
    value: 3
  batch_size:
    value: 128
  epochs:
    value: 10
  lr:
    min: 0.000001
    max: 0.001
  T_max:
    value: 10